demo_arch_test:
  run_type: arch_testing
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 10
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_headless_demo.yaml
    drive: 2.5
  RL:
    normWrapper: false
    useRandStartCond: 1
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward_demo.yaml
    useEarlyTerm: false
    episodes_per_training: 1
    action_choice: [STRETCH]
    observation_choice: [JOINT_POSITION]
    target_speed: 0.4
    policy_network:
      arch: [64, 64]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_demo.yaml
  n_iterations: 200
  n_iterations_testing: 200
  evaluation:
    n_eval_episodes: 2
    cross_seed_eval: false

demo_arch_viewer:
  run_type: arch_testing
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 10
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_viewer_demo.yaml
    drive: 2.5
  RL:
    normWrapper: false
    useRandStartCond: 1
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward_demo.yaml
    useEarlyTerm: false
    episodes_per_training: 1
    action_choice: [STRETCH]
    observation_choice: [JOINT_POSITION]
    target_speed: 0.4
    policy_network:
      arch: [64, 64]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_demo.yaml
  n_iterations: 400
  n_iterations_testing: 400
  evaluation:
    n_eval_episodes: 1
    cross_seed_eval: false

demo_caudal_feedback_viewer:
  run_type: arch_testing
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 10
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_viewer_demo.yaml
    drive: 2.5
  RL:
    normWrapper: false
    useRandStartCond: 1
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward_demo.yaml
    useEarlyTerm: false
    episodes_per_training: 1
    action_choice: [STRETCH]
    observation_choice: [JOINT_POSITION]
    target_speed: 0.4
    policy_network:
      arch: [64, 64]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_demo.yaml
  n_iterations: 400
  n_iterations_testing: 400
  evaluation:
    n_eval_episodes: 1
    cross_seed_eval: false

demo_cpg_swim_viewer:
  run_type: arch_testing
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 0
    c_inter: 10
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_viewer_demo.yaml
    drive: 2.5
  RL:
    normWrapper: false
    useRandStartCond: 1
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward_demo.yaml
    useEarlyTerm: false
    episodes_per_training: 1
    action_choice: [STRETCH]
    observation_choice: [JOINT_POSITION]
    target_speed: 0.4
    policy_network:
      arch: [64, 64]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_demo.yaml
  n_iterations: 400
  n_iterations_testing: 400
  evaluation:
    n_eval_episodes: 1
    cross_seed_eval: false

demo_drl_short_train:
  run_type: train
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 0
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_headless_demo.yaml
    drive: 2.5
  RL:
    normWrapper: false
    useRandStartCond: 1
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward_demo.yaml
    useEarlyTerm: false
    episodes_per_training: 2
    action_choice: [STRETCH]
    observation_choice: [JOINT_POSITION, PHASES, JOINT_VEL]
    phase_preprocessing: sin
    target_speed: 0.4
    policy_network:
      arch: [64, 64]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_demo.yaml
  frames_per_action: 2
  n_iterations: 200
  n_iterations_testing: 200
  training:
    eval_freq: 100
    eval_episodes: 2
  post_training:
    run_test: false
  evaluation:
    n_eval_episodes: 2
    cross_seed_eval: false

demo_drl_short_train_video:
  run_type: train
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 0
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_headless_demo.yaml
    drive: 2.5
  RL:
    normWrapper: false
    useRandStartCond: 1
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward_demo.yaml
    useEarlyTerm: false
    episodes_per_training: 2
    action_choice: [STRETCH]
    observation_choice: [JOINT_POSITION, PHASES, JOINT_VEL]
    phase_preprocessing: sin
    target_speed: 0.4
    policy_network:
      arch: [64, 64]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_demo.yaml
  frames_per_action: 2
  n_iterations: 200
  n_iterations_testing: 200
  training:
    eval_freq: 100
    eval_episodes: 2
  post_training:
    run_test: true
    record_video: true
    video_name: demo_drl_short_train_video.mp4
  evaluation:
    n_eval_episodes: 2
    cross_seed_eval: false

demo_drl_target_speed_quick:
  run_type: train
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 0
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_headless_demo.yaml
    drive: 2.5
  RL:
    normWrapper: true
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward629.yaml
    useEarlyTerm: true
    episodes_per_training: 50
    action_choice: [STRETCH_2]
    observation_choice: [JOINT_POSITION, PHASES, JOINT_VEL]
    phase_preprocessing: sin
    target_speed: 0.25
    policy_network:
      arch: [128, 128]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_mini.yaml
  frames_per_action: 2
  n_iterations: 200
  n_iterations_testing: 200
  training:
    eval_freq: 1000
    eval_episodes: 2
  post_training:
    run_test: false
  evaluation:
    n_eval_episodes: 2
    cross_seed_eval: false

demo_drl_target_speed_full:
  run_type: train
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 0
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_headless_demo.yaml
    drive: 2.5
  RL:
    normWrapper: true
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward629.yaml
    useEarlyTerm: true
    episodes_per_training: 7000
    action_choice: [STRETCH_2]
    observation_choice: [JOINT_POSITION, PHASES, JOINT_VEL]
    phase_preprocessing: sin
    target_speed: 0.25
    policy_network:
      arch: [128, 128]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_1_old_lr.yaml
  frames_per_action: 2
  n_iterations: 200
  n_iterations_testing: 200
  training:
    eval_freq: 100000
    eval_episodes: 5
  post_training:
    run_test: true
  evaluation:
    n_eval_episodes: 5
    cross_seed_eval: true

demo_drl_fast_swim_full:
  run_type: train
  robot_arch:
    init_osci_cond: 0
    s_caudl_weight: 0
    c_inter: 0
    s_caudl_senstivity: SIN
    s_local_senstivity: SIN
    s_local_weight: null
  config:
    animat: config/_ANIMAT/agnathaX_open.yaml
    arena: config/_ARENA/arena_water.yaml
    simulation: config/_SIMULATION/simulation_headless_demo.yaml
    drive: 2.5
  RL:
    normWrapper: true
    useRandStartCondPhases: 9
    RewardFnc: config/RewardFnc_params/reward613.yaml
    useEarlyTerm: true
    episodes_per_training: 10000
    action_choice: [STRETCH]
    observation_choice: [JOINT_POSITION, PHASES, JOINT_VEL]
    phase_preprocessing: sin
    policy_network:
      arch: [128, 128]
      act_fn: Tanh
    PPOparams: config/PPO_params/PPO_1_old_lr.yaml
  frames_per_action: 2
  n_iterations: 200
  n_iterations_testing: 200
  training:
    eval_freq: 100000
    eval_episodes: 5
  post_training:
    run_test: true
  evaluation:
    n_eval_episodes: 5
    cross_seed_eval: true
