units:
  meters: 1.0
  seconds: 1.0
  kilograms: 1.0
timestep: 0.01
n_iterations: 1000
play: true
rtl: 1.0
fast: false
headless: false
show_progress: true
zoom: 1
free_camera: false
top_camera: false
rotating_camera: false
video: ''
video_fps: 30
video_name: video
video_yaw: 30
video_pitch: 45
video_distance: 1
video_offset: !!python/tuple
- 0
- 0
- 0
video_filter: null
video_resolution: !!python/tuple
- 1280
- 720
gravity: !!python/tuple
- 0
- 0
- -9.81
num_sub_steps: 0
n_solver_iters: 100
residual_threshold: 1.0e-08
visual_scale: 1.0
cone: elliptic
solver: Newton
integrator: implicit
impratio: 10.0
mpr_iterations: 10000
mpr_tolerance: 1.0e-16
noslip_iterations: 0
noslip_tolerance: 1.0e-16
opengl2: false
lcp: dantzig
cfm: 0
erp: 0
contact_erp: 0
friction_erp: 0
max_num_cmd_per_1ms: 1000000000
report_solver_analytics: 0
